BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Model;
using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Filters;
using BSUIR.TermWork.ImageViewer.UI.WebSite.Mappers;
using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Comment;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [RoutePrefix("user/{key:int}/album/{albumKey:int}/image/{imageKey:int}")]
    [CustomAuthFilter]
    public class CommentController : BaseController
    {
        private readonly ICommentMapper _commentMapper;
        private readonly IImageAlbumService _imageAlbumService;
        private readonly ICommentService _commentService;
        private readonly IMembershipService _membershipService;

        public CommentController(ICommentMapper commentMapper, IImageAlbumService imageAlbumService, ICommentService commentService, IMembershipService membershipService)
        {
            this._commentMapper = commentMapper;
            this._imageAlbumService = imageAlbumService;
            this._commentService = commentService;
            this._membershipService = membershipService;
        }

        [HttpGet]
        [Route("comments")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult Comments(int? imageKey)
        {
            //ViewBag.Key = RouteData.Values["key"];
            //ViewBag.AlbumKey = RouteData.Values["albumKey"];
            //ViewBag.ImageKey = RouteData.Values["imageKey"];

            IList<CommentListItemViewModel> result = new List<CommentListItemViewModel>();

            if (imageKey.HasValue)
            {
                try
                {
                    Image image = this._imageAlbumService.GetImageByKey(imageKey.Value);
                    if (image != null)
                    {
                        result =
                            this._commentService.GetCommentsForImage(image)
                                .Select(p => this._commentMapper.BuildListItem(p))
                                .ToList();
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }
            return this.PartialView("_ListComment", result);
        }

        [HttpGet]
        [Route("comment/add")]
        [ViewBagPopulatorFilter]
        [AjaxRequestOnlyFilter]
        public PartialViewResult CreateComment(int? imageKey)
        {
            //ViewBag.Key = RouteData.Values["key"];
            //ViewBag.AlbumKey = RouteData.Values["albumKey"];
            //ViewBag.ImageKey = RouteData.Values["imageKey"];

            var result = new CommentCreateViewModel();
            return this.PartialView("_CreateComment", result);
        }

        [HttpPost]
        [Route("comment/add")]
        [AjaxRequestOnlyFilter]
        public ActionResult CreateComment(int? imageKey, CommentCreateViewModel viewModel)
        {
            bool result = false;
            var user = this.User.Identity as CustomIdentity;
            if (this.ModelState.IsValid && viewModel != null)
            {
                try
                {
                    User owner = this._membershipService.GetUserByKey(user.Id);
                    Image image = this._imageAlbumService.GetImageByKey(imageKey.Value);
                    Comment comment = this._commentMapper.BuildComment(viewModel);
                    comment.Owner = owner;
                    comment.Image = image;
                    this._commentService.CreateComment(owner, image, comment);
                    result = true;
                }
                catch (Exception)
                {
                    this.ModelState.AddModelError(string.Empty, Resources.Resources.OperationFailure);
                }
            }
            else
            {
                this.ModelState.AddModelError(string.Empty, Resources.Resources.OperationFailure);
            }

            if (result)
            {
                return this.Json(new { success = result });
            }
            return this.PartialView("_CreateComment", viewModel);
        }

        [HttpGet]
        [Route("comment/remove/{commentKey:int}")]
        [AjaxRequestOnlyFilter]
        public PartialViewResult RemoveComment(int? commentKey)
        {
            CommentCreateViewModel result = null;
            if (commentKey.HasValue)
            {
                try
                {
                    Comment comment = this._commentService.GetCommentByKey(commentKey.Value);
                    if (comment != null)
                    {
                        result = this._commentMapper.BuildCreate(comment);
                    }
                    else
                    {
                        this.TempData[Constants.TempDataErrorMessage] = "Comment is missing.";
                        return this.PartialView("_ErrorModal");
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }
            else
            {
                this.TempData[Constants.TempDataErrorMessage] = "Comment is missing.";
                return this.PartialView("_ErrorModal");
            }
            return this.PartialView("_RemoveComment", result);
        }

        [HttpPost]
        [Route("comment/remove/{commentKey:int}")]
        [AjaxRequestOnlyFilter]
        public ActionResult RemoveComment(CommentCreateViewModel viewModel)
        {
            bool result = false;
            if (viewModel != null)
            {
                try
                {
                    Comment comment = this._commentService.GetCommentByKey(viewModel.Key);
                    if (comment != null)
                    {
                        result = this._commentService.RemoveComment(comment);
                    }
                    else
                    {
                        this.TempData[Constants.TempDataErrorMessage] = "Comment is missing.";
                        return this.PartialView("_ErrorModal");
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }
            else
            {
                this.TempData[Constants.TempDataErrorMessage] = "Comment is missing.";
                return this.PartialView("_ErrorModal");
            }
            if (result)
            {
                return this.Json(new { success = result });
            }
            return this.PartialView("_Success");
        }
	}
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/PersonalPageController.cs
using System;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Filters;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [RoutePrefix("user/{key:int}")]
    [CustomAuthFilter]
    public class PersonalPageController : BaseController
    {
        private readonly ISubscriptionService _subscriptionService;
        private readonly IMembershipService _membershipService;
        private readonly IFriendshipService _friendshipService;

        public PersonalPageController(
            ISubscriptionService subscriptionService,
            IMembershipService membershipService,
            IFriendshipService friendshipService)
        {
            this._subscriptionService = subscriptionService;
            this._membershipService = membershipService;
            this._friendshipService = friendshipService;
        }

        [HttpGet]
        [ViewBagPopulatorFilter]
        [Route("index")]
        public ActionResult Index(int? key)
        {
            this.UpdateSubscriptions(this._subscriptionService);
            this.UpdateFriendsList(this._friendshipService);
            this.ReleaseUpToDateSubscriptions(this._membershipService, this._subscriptionService);
            try
            {
                if (!(key.HasValue && this._membershipService.GetUserByKey(key.Value) != null))
                {
                    return this.RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                return this.RedirectToAction("Index", "Home");
            }

            return this.View();
        }

        [HttpGet]
        [Route("navigationbar")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult NavigationBar()
        {
            return this.PartialView("_NavigationSidebar");
        }
    }
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Comment/_CreateComment.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Comment

@model CommentCreateViewModel
           
<div class="modal fade" id="create-comment-modal" tabindex="-1" role="dialog" aria-labelledby="create-comment-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="create-comment-modal-header">Create Comment</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        @using (this.Html.BeginForm("CreateComment", "Comment", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    @(this.Html.ValidationSummary(true))
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <label for="inputContent">Content</label>
                                    <p>@(this.Html.ValidationMessageFor(p => p.Content))</p>
                                    @(this.Html.TextAreaFor(p => p.Content, new { placeholder = "Content", @class = "form-control", id = "inputContent" }))
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <button class="btn btn-primary" type="submit"><i class="fa fa-cog fa-fw"></i> Create</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Comment/_ListComment.cshtml
@using System.Globalization
@using BSUIR.TermWork.ImageViewer.Model
@using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication
@using BSUIR.TermWork.ImageViewer.UI.WebSite.Helpers
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Comment

@model IList<CommentListItemViewModel>

<div id="user-comment-list" class="row">
    <div class="col-md-12">
        @for (int i = 0; i < @Model.Count; ++i)
        {
            <div class="panel panel-info">
                <div class="panel-heading">
                    <a href="@Url.Action("Index", "PersonalPage", new { key = ViewBag.Key} )">@Model[i].UserName</a>
                    @Model[i].CreationDate.ToLocalTime().ToString(CultureInfo.InvariantCulture)
                </div>
                <div class="panel-body">
                    @Model[i].Content
                    @if (User.IsInRole(RoleName.Administrator.ToString()) || User.IsInRole(RoleName.Moderator.ToString()))
                    {
                         @(this.Html.AjaxModalWindow("Remove ", this.Url.Action("RemoveComment", "Comment",
                          new { key = ViewBag.Key, albumKey = ViewBag.AlbumKey, imageKey = ViewBag.ImageKey, commentKey = @Model[i].Key }),
                          "remove-comment-modal",
                          "user-account-control",
                          "btn btn-danger pull-right",
                          "fa fa-crosshairs",
                          string.Concat(@"{ ""commentKey"": """, this.Model[i].Key, @"""  }")))
                    }
            </div>
        </div>
        <hr class="comment-item-divider" />
        }
    </div>
    <div class="btn-group">
        @(this.Html.AjaxModalWindow("Leave comment ", this.Url.Action("CreateComment", "Comment",
              new { key = ViewBag.Key, albumKey = ViewBag.AlbumKey, imageKey = ViewBag.ImageKey }),
              "create-comment-modal",
              "user-account-control",
              "btn btn-info",
              "fa fa-edit",
              ""))
    </div>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Comment/_RemoveComment.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Comment

@model CommentCreateViewModel

<div class="modal fade" id="remove-comment-modal" tabindex="-1" role="dialog" aria-labelledby="remove-comment-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="remove-comment-modal-header">Remove Comment</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        @using (this.Html.BeginForm("RemoveComment", "Comment", new { commentKey = Model.Key }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.HiddenFor(p => p.Key)
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <p>Do you really want to remove comment?</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <button class="btn btn-danger" type="submit"><i class="fa fa-crosshairs fa-fw"></i> Remove</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>