BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/ChatController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Model;
using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Filters;
using BSUIR.TermWork.ImageViewer.UI.WebSite.Mappers;
using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Chat;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [CustomAuthFilter]
    [RoutePrefix("user/{key:int}/chat")]
    public sealed class ChatController : BaseController
    {
        private readonly IMessageService _messageService;
        private readonly IMembershipService _membershipService;
        private readonly IChatMapper _chatMapper;

        public ChatController(
            IMessageService messageService,
            IMembershipService membershipService,
            IChatMapper chatMapper)
        {
            this._messageService = messageService;
            this._membershipService = membershipService;
            this._chatMapper = chatMapper;
        }

        [HttpGet]
        [Route("getdaymessages")]
        [AjaxRequestOnlyFilter]

        public PartialViewResult GetDayMessages(int? friendKey)
        {
            var userIdentity = this.User.Identity as CustomIdentity;
            IList<MessageViewModel> result = new List<MessageViewModel>();

            if (friendKey.HasValue)
            {
                User currentUser = this._membershipService.GetUserByKey(userIdentity.Id);
                User friend = this._membershipService.GetUserByKey(friendKey.GetValueOrDefault());
                IEnumerable<Message> messages = this._messageService.GetDayChatMessages(
                    currentUser,
                    friend);
                result = messages.Select(p => this._chatMapper.MapMessage(p)).ToList();
            }

            return this.PartialView("_MessageList", result);
        }

        [HttpGet]
        [Route("dualchatroom")]
        [AjaxRequestOnlyFilter]
        public PartialViewResult DualChatRoom(int? friendKey)
        {
            var userIdentity = this.User.Identity as CustomIdentity;
            var chatViewModel = new DualChatRoomViewModel();

            if (friendKey.HasValue)
            {
                User currentUser = this._membershipService.GetUserByKey(userIdentity.Id);
                User friend = this._membershipService.GetUserByKey(friendKey.GetValueOrDefault());
                IEnumerable<Message> messages = this._messageService.GetDayChatMessages(
                    currentUser,
                    friend);
                chatViewModel = this._chatMapper.Map(currentUser, friend);
                chatViewModel.Messages =
                    messages.Select(p => this._chatMapper.MapMessage(p)).ToList();
            }

            return this.PartialView("_DualChatRoom", chatViewModel);
        }    

    }
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/FriendshipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Model;
using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Filters;
using BSUIR.TermWork.ImageViewer.UI.WebSite.Mappers;
using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Friendship;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [CustomAuthFilter]
    [RoutePrefix("user/{key:int}/friends")]
    public sealed class FriendshipController : BaseController
    {
        private readonly IFriendshipService _friendshipService;
        private readonly IMembershipService _membershipService;
        private readonly ISubscriptionService _subscriptionService;
        private readonly IFriendshipMapper _friendshipMapper;

        public FriendshipController(
            IFriendshipService friendshipService,
            IMembershipService membershipService,
            ISubscriptionService subscriptionService,
            IFriendshipMapper friendshipMapper)
        {
            this._friendshipService = friendshipService;
            this._membershipService = membershipService;
            this._subscriptionService = subscriptionService;
            this._friendshipMapper = friendshipMapper;
        }

        [HttpGet]
        [Route("removefriend")]
        [ViewBagPopulatorFilter]
        [AjaxRequestOnlyFilter]
        public PartialViewResult RemoveFriend(int? key)
        {
            FriendRequestCreateViewModel model;
            if (key.HasValue)
            {
                model = new FriendRequestCreateViewModel();
                model.Key = key.Value;
            }
            else
            {
                this.TempData[Constants.TempDataErrorMessage] = "User is missing.";
                return this.PartialView("_ErrorModal");
            }

            return this.PartialView("_RemoveFriend", model);
        }

        [HttpPost]
        [Route("removefriend")]
        [ViewBagPopulatorFilter]
        [AjaxRequestOnlyFilter]
        public ActionResult RemoveFriend(FriendRequestCreateViewModel viewModel)
        {
            var user = User.Identity as CustomIdentity;

            if (viewModel != null)
            {
                try
                {
                    User firstFriend = this._membershipService.GetUserByKey(user.Id);
                    User secondFriend =
                        this._membershipService.GetUserByKey(viewModel.Key.GetValueOrDefault());
                    this._friendshipService.RemoveFriend(firstFriend, secondFriend);
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }

            return this.Json(new { success = true });
        }

        [HttpGet]
        [Route("sendfriendshiprequest")]
        [ViewBagPopulatorFilter]
        [AjaxRequestOnlyFilter]
        public PartialViewResult SendFriendshipRequest(int? key)
        {
            FriendRequestCreateViewModel model;
            if (key.HasValue)
            {
                model = new FriendRequestCreateViewModel();
                model.Key = key.Value;
            }
            else
            {
                this.TempData[Constants.TempDataErrorMessage] = "User is missing.";
                return this.PartialView("_ErrorModal");
            }

            return this.PartialView("_FriendshipRequest", model);
        }

        [HttpPost]
        [Route("sendfriendshiprequest")]
        [ViewBagPopulatorFilter]
        [AjaxRequestOnlyFilter]
        public ActionResult SendFriendshipRequest(FriendRequestCreateViewModel viewModel)
        {
            bool result = true;
            var user = User.Identity as CustomIdentity;

            if (viewModel != null)
            {
                try
                {
                    User sender = this._membershipService.GetUserByKey(user.Id);
                    User receiver =
                        this._membershipService.GetUserByKey(viewModel.Key.GetValueOrDefault());
                    this._friendshipService.SendRequest(sender, receiver);
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }

            }

            if (result)
            {
                return this.Json(new { success = true });
            }

            return this.PartialView("_Success");
        }

        [HttpGet]
        [Route("friendshiprequestlist")]
        [ChildActionOnly]
        [ViewBagPopulatorFilter]
        public PartialViewResult FriendshipRequestList(int? key)
        {
            var user = User.Identity as CustomIdentity;
            IList<FriendshipRequestViewModel> result = new List<FriendshipRequestViewModel>();

            User receiver = this._membershipService.GetUserByKey(user.Id);
            if (receiver != null)
            {
                result =
                    this._friendshipService.GetUnconfirmedRequests(receiver)
                        .Select(p => this._friendshipMapper.BuildViewModel(p))
                        .ToList();
            }

            return this.PartialView("_FriendshipRequestList", result);
        }

        [HttpGet]
        [Route("confirmrequest")]
        [AjaxRequestOnlyFilter]
        [ViewBagPopulatorFilter]
        public PartialViewResult ConfirmRequest(int? senderKey)
        {
            var user = this.User.Identity as CustomIdentity;
            var answerViewModel = new FriendshipAnswerViewModel();
            answerViewModel.ReceiverKey = user.Id;
            answerViewModel.SenderKey = senderKey;

            return this.PartialView("_ConfirmFriendshipRequest", answerViewModel);
        }

        [HttpPost]
        [Route("confirmrequest")]
        [AjaxRequestOnlyFilter]
        [ViewBagPopulatorFilter]
        public ActionResult ConfirmRequest(FriendshipAnswerViewModel answerViewModel)
        {
            var user = this.User.Identity as CustomIdentity;

            if (answerViewModel != null)
            {
                try
                {
                    User receiver = this._membershipService.GetUserByKey(user.Id);
                    User sender =
                        this._membershipService.GetUserByKey(
                            answerViewModel.SenderKey.GetValueOrDefault());
                    this._friendshipService.ConfirmRequest(sender, receiver);
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }
            
            return this.Json(new { success = true });
        }

        [HttpGet]
        [Route("declinerequest")]
        [AjaxRequestOnlyFilter]
        [ViewBagPopulatorFilter]
        public PartialViewResult DeclineRequest(int? senderKey)
        {
            var user = this.User.Identity as CustomIdentity;
            var answerViewModel = new FriendshipAnswerViewModel();
            answerViewModel.ReceiverKey = user.Id;
            answerViewModel.SenderKey = senderKey;

            return this.PartialView("_DeclineFriendshipRequest", answerViewModel);
        }

        [HttpGet]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        [Route("friendslistnavbar")]
        public PartialViewResult FriendsListNavbar()
        {
            var userIdentity = this.User.Identity as CustomIdentity;
            User user = this._membershipService.GetUserByKey(userIdentity.Id);
            IList<FriendViewModel> friends =
                this._friendshipService.GetFriends(user)
                    .Select(p => this._friendshipMapper.Build(p))
                    .ToList();

            return this.PartialView("_FriendsListNavbar", friends);
        }

        [HttpPost]
        [Route("declinerequest")]
        [AjaxRequestOnlyFilter]
        [ViewBagPopulatorFilter]
        public ActionResult DeclineRequest(FriendshipAnswerViewModel answerViewModel)
        {
            var user = this.User.Identity as CustomIdentity;

            if (answerViewModel != null)
            {
                try
                {
                    User receiver = this._membershipService.GetUserByKey(user.Id);
                    User sender =
                        this._membershipService.GetUserByKey(
                            answerViewModel.SenderKey.GetValueOrDefault());
                    this._friendshipService.DeclineRequest(sender, receiver);
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }

            return this.Json(new { success = true });
        }

        [HttpGet]
        [Route("navigationbar")]
        [ChildActionOnly]
        [ViewBagPopulatorFilter]
        public PartialViewResult NavigationBar()
        {
            return this.PartialView("_FriendshipNavbar");
        }

        [HttpGet]
        [Route("index")]
        [ViewBagPopulatorFilter]
        public ActionResult Index(int? key)
        {
            this.UpdateSubscriptions(this._subscriptionService);
            this.UpdateFriendsList(this._friendshipService);
            this.ReleaseUpToDateSubscriptions(this._membershipService, this._subscriptionService);
            try
            {
                if (!(key.HasValue && this._membershipService.GetUserByKey(key.Value) != null))

BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Filters;
using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Notification;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [CustomAuthFilter]
    [RoutePrefix("user/{key:int}/notifications")]
    public sealed class NotificationController : BaseController
    {
        private readonly IFriendshipService _friendshipService;
        private readonly IMembershipService _membershipService;

        public NotificationController(
            IFriendshipService friendshipService,
            IMembershipService membershipService)
        {
            this._friendshipService = friendshipService;
            this._membershipService = membershipService;
        }

        [HttpGet]
        [Route("notificationlist")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult NotificationList()
        {
            var model = new NotificationCountViewModel();
            var user = this.User.Identity as CustomIdentity;

            var sender = this._membershipService.GetUserByKey(user.Id);
            model.Count = this._friendshipService.GetUnconfirmedRequests(sender).Count();

            return this.PartialView("_Notifications", model);
        }
    }
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/OperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Filters;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [CustomAuthFilter]
    [RoutePrefix("user/{key:int}/operations")]
    public sealed class OperationController : BaseController
    {
        private readonly IFriendshipService _friendshipService;

        public OperationController(IFriendshipService friendshipService)
        {
            this._friendshipService = friendshipService;
        }

        [HttpGet]
        [Route("friendshipoperation")]
        [ViewBagPopulatorFilter]
        [FriendshipVerificationFilter]
        [ChildActionOnly]
        public PartialViewResult FriendshipOperation()
        {
            return this.PartialView("_FriendshipOperation");
        }

        [HttpGet]
        [Route("operationlist")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult OperationList()
        {
            return this.PartialView("_Operations");
        }
    }
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Friendship/FriendshipIndex.cshtml
@{
    ViewBag.Title = "Friends";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row navbar-margin">
    <div class="col-md-3">
        @{Html.RenderAction("NavigationBar", "Friendship");}
    </div>
    <div id="friendship-list" class="col-md-9">
        <h1>Friendship Requests</h1>
        @{ Html.RenderAction("FriendshipRequestList", "Friendship");}
    </div>
</div>

@section scripts 
{
    <script type="text/javascript" src="~/Scripts/friendship/friendshipactions.js"></script>  
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Friendship/_ConfirmFriendshipRequest.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Friendship

@model FriendshipAnswerViewModel

<div class="modal fade" id="confirm-request-modal" tabindex="-1" role="dialog" aria-labelledby="confirm-request-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="confirm-request-modal-header">Confirm Request</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        @using (this.Html.BeginForm("ConfirmRequest", "Friendship", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.HiddenFor(p => p.SenderKey)
                            @Html.HiddenFor(p => p.ReceiverKey)
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <p>Do you really want to make friends with this person?</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <button class="btn btn-success" type="submit"><i class="fa fa-crosshairs fa-fw"></i> Accept</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Friendship/_DeclineFriendshipRequest.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Friendship

@model FriendshipAnswerViewModel

<div class="modal fade" id="decline-request-modal" tabindex="-1" role="dialog" aria-labelledby="decline-request-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="decline-request-modal-header">Decline Request</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        @using (this.Html.BeginForm("DeclineRequest", "Friendship", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.HiddenFor(p => p.SenderKey)
                            @Html.HiddenFor(p => p.ReceiverKey)
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <p>Do you really want to decline this friendship request?</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <button class="btn btn-danger" type="submit"><i class="fa fa-crosshairs fa-fw"></i> Decline</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Friendship/_FriendsListNavbar.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.Helpers
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Friendship

@model System.Collections.Generic.IList<FriendViewModel>

<li id="friends-navbar-list" class="active">
    <a href="#">Friends</a>
    <ul class="nav">
    @for (int i = 0; i < Model.Count; ++i)
    {
        <li class="">
            @Html.AjaxLinkModalWindow(@Model[i].FirstName + " " + @Model[i].LastName, Url.Action("DualChatRoom", "Chat", new { friendKey = @Model[i].Key }), "dual-chat-room-modal", "user-account-control", "", "fa fa-cogs pull-right", "")
        </li>
    }
    </ul>
</li>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Friendship/_FriendshipNavbar.cshtml
<div class="bs-sidebar hidden-print affix" role="complementary">
    <ul class="nav bs-sidenav">
        @{ Html.RenderAction("AlbumHeaders", "Album", new { key = ViewBag.Key });}
        @{ Html.RenderAction("Subscribers", "Subscription", new { key = ViewBag.Key });}
        @{ Html.RenderAction("OperationList", "Operation", new { key = ViewBag.Key }); }
        @{ Html.RenderAction("NotificationList", "Notification", new { key = ViewBag.Key }); }
        @{ Html.RenderAction("FriendsListNavbar", "Friendship", new { key = ViewBag.Key });}
    </ul>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Friendship/_FriendshipRequest.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Friendship

@model FriendRequestCreateViewModel
           
<div class="modal fade" id="friendship-request-modal" tabindex="-1" role="dialog" aria-labelledby="friendship-request-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="friendship-request-modal-header">Make friends</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        @using (this.Html.BeginForm("SendFriendshipRequest", "Friendship", new { key = Model.Key }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.HiddenFor(p => p.Key)
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <p>Do you really want to make friends?</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <button class="btn btn-info" type="submit"><i class="fa fa-users fa-fw"></i> Make friends</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Friendship/_FriendshipRequestList.cshtml
@using System.Globalization
@using BSUIR.TermWork.ImageViewer.UI.WebSite.Helpers
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Friendship

@model System.Collections.Generic.IList<FriendshipRequestViewModel>

@for (int i = 0; i < this.Model.Count; ++i)
{
    <div class="row well well-lg">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 data-key="@Model[i].UserKey">@Model[i].FirstName @Model[i].LastName</h3>
                </div>
                <div class="panel-body">
                    <p align="justify">
                        @Model[i].Email @Model[i].RequestDate.ToString(CultureInfo.InvariantCulture)
                    </p>
                </div>
                <div class="btn-group" style="margin-bottom: 10px; margin-left: 10px;">
                    @(this.Html.AjaxModalWindow("Accept ", this.Url.Action("ConfirmRequest", "Friendship", new { senderKey = this.Model[i].UserKey }), "confirm-request-modal", "user-account-control", "btn btn-success", "fa fa-check-square-o", string.Empty))
                    @(this.Html.AjaxModalWindow("Decline ", this.Url.Action("DeclineRequest", "Friendship", new { senderKey = this.Model[i].UserKey }), "decline-request-modal", "user-account-control", "btn btn-danger", "fa fa-arrows-alt", string.Empty))
                </div>
            </div>
        </div>
    </div>
    <hr class="album-item-divider" />
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Friendship/_RemoveFriend.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Friendship

@model FriendRequestCreateViewModel

<div class="modal fade" id="remove-friend-modal" tabindex="-1" role="dialog" aria-labelledby="remove-friend-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="remove-friend-modal-header">Remove friend</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        @using (this.Html.BeginForm("RemoveFriend", "Friendship", new { key = Model.Key }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.HiddenFor(p => p.Key)
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <p>Do you really want to break friendship?</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <button class="btn btn-danger" type="submit"><i class="fa fa-arrows-alt"></i> Break</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>