BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/PersonalPageController.cs
using System;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Filters;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [RoutePrefix("user/{key:int}")]
    [CustomAuthFilter]
    public class PersonalPageController : BaseController
    {
        private readonly ISubscriptionService _subscriptionService;
        private readonly IMembershipService _membershipService;
        private readonly IFriendshipService _friendshipService;

        public PersonalPageController(
            ISubscriptionService subscriptionService,
            IMembershipService membershipService,
            IFriendshipService friendshipService)
        {
            this._subscriptionService = subscriptionService;
            this._membershipService = membershipService;
            this._friendshipService = friendshipService;
        }

        [HttpGet]
        [ViewBagPopulatorFilter]
        [Route("index")]
        public ActionResult Index(int? key)
        {
            this.UpdateSubscriptions(this._subscriptionService);
            this.UpdateFriendsList(this._friendshipService);
            this.ReleaseUpToDateSubscriptions(this._membershipService, this._subscriptionService);
            try
            {
                if (!(key.HasValue && this._membershipService.GetUserByKey(key.Value) != null))
                {
                    return this.RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                return this.RedirectToAction("Index", "Home");
            }

            return this.View();
        }

        [HttpGet]
        [Route("navigationbar")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult NavigationBar()
        {
            return this.PartialView("_NavigationSidebar");
        }
    }
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Model;
using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.WebSite.Mappers;
using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Search;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [CustomAuthFilter]
    [RoutePrefix("search")]
    public class SearchController : Controller
    {
        private readonly ISearchService _searchService;
        private readonly ISearchMapper _searchMapper;

        public SearchController(ISearchService searchService, ISearchMapper searchMapper)
        {
            this._searchService = searchService;
            this._searchMapper = searchMapper;
        }

        [HttpGet]
        [ChildActionOnly]
        [Route("searchbar")]
        public PartialViewResult SearchBar()
        {
            var result = new SearchFormViewModel();
            return this.PartialView("_SearchBar", result);
        }

        [HttpPost]
        [Route("searchbar")]
        public ActionResult PerformSearch(SearchFormViewModel viewModel)
        {
            var result = new List<SearchResultViewModel>();
            if (viewModel != null)
            {
                try
                {
                    IList<Album> albums = this._searchService.SearchAlbums(viewModel.SearchString);
                    IList<Image> images = this._searchService.SearchImages(viewModel.SearchString);
                    for (int i = 0; i < albums.Count; ++i)
                    {
                        SearchResultViewModel model = this._searchMapper.BuildResult(albums[i]);
                        model.Reference = this.Url.Action(
                            "Index",
                            "Image",
                            new { key = albums[i].Owner.Key, albumKey = albums[i].Key });
                        result.Add(model);
                    }

                    for (int i = 0; i < images.Count; ++i)
                    {
                        SearchResultViewModel model = this._searchMapper.BuildResult(images[i]);
                        model.Reference = this.Url.Action(
                            "ViewImage",
                            "Image",
                            new { key = images[i].Owner.Key, albumKey = images[i].Album.Key, imageKey = images[i].Key });
                        result.Add(model);
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }

            return this.View("SearchResult", result);
        }
    }
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Shared/_ErrorModal.cshtml
@using BSUIR.TermWork.ImageViewer.UI.Infrastructure

<div class="modal fade" id="error-modal" tabindex="-1" role="dialog" aria-labelledby="error-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="edit-album-modal-header">Error</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        <div class="validation-summary-errors">
                            @if (TempData[Constants.TempDataErrorMessage] != null)
                            {
                                @TempData[Constants.TempDataErrorMessage]
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Shared/_Footer.cshtml
@using System
<footer>
    <div class="footer">
        <div class="container">
            <p class="credit">
                &copy; BSUIR, FKSIS, Raman But-Husaim, @DateTime.UtcNow.Year ·
                <a href="@Url.Action("Privacy", "Home")">Privacy</a>
                ·
                <a href="@Url.Action("Terms", "Home")">Terms</a>
            </p>
        </div>
    </div>
</footer>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Shared/_Layout.cshtml
@using BSUIR.TermWork.ImageViewer.Model
@using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication
@{
    var userIdentity = User.Identity as CustomIdentity;
}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
        <title>@(this.ViewBag.Title)</title>
        @Styles.Render("~/Content/bootstrap")
        @Styles.Render("~/Content/bootstrap-theme")
        @Scripts.Render("~/bundles/modernizr")
        <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
        <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
        <meta name="description" content="The image viewer website." />
    </head>
    <body>
        <div id="wrap">
            <header>
                <div class="navbar navbar-inverse navbar-fixed-top">
                    <div class="container">
                        <div class="navbar-header">
                            <a href="@(this.Url.Action("Index", "Home"))">
                                <img class="pull-left" src="~/Content/images/logo_sm.png" />
                            </a>
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="@(this.Url.Action("Index", "Home"))">Social Network</a>
                        </div>
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav">
                                <li><a href="@(this.Url.Action("Index", "Home"))">Home</a></li>
                                <li><a href="@(this.Url.Action("About", "Home"))">About</a></li>
                                @if (userIdentity != null)
                                {
                                    <li><a href="@(this.Url.Action("Index", "PersonalPage", new { key = userIdentity.Id }))">Albums</a></li>
                                    if (User.IsInRole(RoleName.Administrator.ToString()))
                                    {
                                        <li><a href="@(this.Url.Action("Index", "Account"))">Admin</a></li>
                                    }
                                }
                            </ul>
                            @if (@Request.IsAuthenticated)
                            {
                                {this.Html.RenderAction("SearchBar", "Search");}
                            }
                            <ul id="user-signin-data" class="nav navbar-nav pull-right">
                                @(this.Html.Action("GetUserInfo", "Account"))
                            </ul>
                        </div>
                    </div>
                </div>
            </header>
            <div class="container">
                <div id="user-account-control"></div>
                @(this.RenderBody())  
            </div>
        </div>

        @(this.Html.Partial("_Footer"))

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/moment")
        <script type="text/javascript" src="~/Scripts/account/account.js"></script>
        <script type="text/javascript" src="~/Scripts/home/searchbar.js"></script>
        <script type="text/javascript" src="~/Scripts/jquery.signalR-2.0.3.js"></script>
        @*<script type="text/javascript" src="~/Scripts/hubs/hubs.js"></script>*@
        <script type="text/javascript" src="~/messaging/js"></script>
        <script type="text/javascript" src="~/Scripts/chat/chat.js"></script>
        @(this.RenderSection("scripts", false))
    </body>
</html>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Shared/_Success.cshtml
@using BSUIR.TermWork.ImageViewer.UI.Infrastructure

<div class="modal fade" id="error-modal" tabindex="-1" role="dialog" aria-labelledby="error-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="edit-album-modal-header">Error</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        <div class="validation-summary-errors">
                            @if (TempData[Constants.TempDataSuccess] != null)
                            {
                                @TempData[Constants.TempDataSuccess]
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>