BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Model;
using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Filters;
using BSUIR.TermWork.ImageViewer.UI.WebSite.Mappers;
using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Comment;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [RoutePrefix("user/{key:int}/album/{albumKey:int}/image/{imageKey:int}")]
    [CustomAuthFilter]
    public class CommentController : BaseController
    {
        private readonly ICommentMapper _commentMapper;
        private readonly IImageAlbumService _imageAlbumService;
        private readonly ICommentService _commentService;
        private readonly IMembershipService _membershipService;

        public CommentController(ICommentMapper commentMapper, IImageAlbumService imageAlbumService, ICommentService commentService, IMembershipService membershipService)
        {
            this._commentMapper = commentMapper;
            this._imageAlbumService = imageAlbumService;
            this._commentService = commentService;
            this._membershipService = membershipService;
        }

        [HttpGet]
        [Route("comments")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult Comments(int? imageKey)
        {
            //ViewBag.Key = RouteData.Values["key"];
            //ViewBag.AlbumKey = RouteData.Values["albumKey"];
            //ViewBag.ImageKey = RouteData.Values["imageKey"];

            IList<CommentListItemViewModel> result = new List<CommentListItemViewModel>();

            if (imageKey.HasValue)
            {
                try
                {
                    Image image = this._imageAlbumService.GetImageByKey(imageKey.Value);
                    if (image != null)
                    {
                        result =
                            this._commentService.GetCommentsForImage(image)
                                .Select(p => this._commentMapper.BuildListItem(p))
                                .ToList();
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }
            return this.PartialView("_ListComment", result);
        }

        [HttpGet]
        [Route("comment/add")]
        [ViewBagPopulatorFilter]
        [AjaxRequestOnlyFilter]
        public PartialViewResult CreateComment(int? imageKey)
        {
            //ViewBag.Key = RouteData.Values["key"];
            //ViewBag.AlbumKey = RouteData.Values["albumKey"];
            //ViewBag.ImageKey = RouteData.Values["imageKey"];

            var result = new CommentCreateViewModel();
            return this.PartialView("_CreateComment", result);
        }

        [HttpPost]
        [Route("comment/add")]
        [AjaxRequestOnlyFilter]
        public ActionResult CreateComment(int? imageKey, CommentCreateViewModel viewModel)
        {
            bool result = false;
            var user = this.User.Identity as CustomIdentity;
            if (this.ModelState.IsValid && viewModel != null)
            {
                try
                {
                    User owner = this._membershipService.GetUserByKey(user.Id);
                    Image image = this._imageAlbumService.GetImageByKey(imageKey.Value);
                    Comment comment = this._commentMapper.BuildComment(viewModel);
                    comment.Owner = owner;
                    comment.Image = image;
                    this._commentService.CreateComment(owner, image, comment);
                    result = true;
                }
                catch (Exception)
                {
                    this.ModelState.AddModelError(string.Empty, Resources.Resources.OperationFailure);
                }
            }
            else
            {
                this.ModelState.AddModelError(string.Empty, Resources.Resources.OperationFailure);
            }

            if (result)
            {
                return this.Json(new { success = result });
            }
            return this.PartialView("_CreateComment", viewModel);
        }

        [HttpGet]
        [Route("comment/remove/{commentKey:int}")]
        [AjaxRequestOnlyFilter]
        public PartialViewResult RemoveComment(int? commentKey)
        {
            CommentCreateViewModel result = null;
            if (commentKey.HasValue)
            {
                try
                {
                    Comment comment = this._commentService.GetCommentByKey(commentKey.Value);
                    if (comment != null)
                    {
                        result = this._commentMapper.BuildCreate(comment);
                    }
                    else
                    {
                        this.TempData[Constants.TempDataErrorMessage] = "Comment is missing.";
                        return this.PartialView("_ErrorModal");
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }
            else
            {
                this.TempData[Constants.TempDataErrorMessage] = "Comment is missing.";
                return this.PartialView("_ErrorModal");
            }
            return this.PartialView("_RemoveComment", result);
        }

        [HttpPost]
        [Route("comment/remove/{commentKey:int}")]
        [AjaxRequestOnlyFilter]
        public ActionResult RemoveComment(CommentCreateViewModel viewModel)
        {
            bool result = false;
            if (viewModel != null)
            {
                try
                {
                    Comment comment = this._commentService.GetCommentByKey(viewModel.Key);
                    if (comment != null)
                    {
                        result = this._commentService.RemoveComment(comment);
                    }
                    else
                    {
                        this.TempData[Constants.TempDataErrorMessage] = "Comment is missing.";
                        return this.PartialView("_ErrorModal");
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }
            else
            {
                this.TempData[Constants.TempDataErrorMessage] = "Comment is missing.";
                return this.PartialView("_ErrorModal");
            }
            if (result)
            {
                return this.Json(new { success = result });
            }
            return this.PartialView("_Success");
        }
	}
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BSUIR.TermWork.ImageViewer.Model;
using BSUIR.TermWork.ImageViewer.Services.Contracts;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Authentication;
using BSUIR.TermWork.ImageViewer.UI.Infrastructure.Filters;
using BSUIR.TermWork.ImageViewer.UI.WebSite.Mappers;
using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Image;

namespace BSUIR.TermWork.ImageViewer.UI.WebSite.Controllers
{
    [RoutePrefix("user/{key:int}/album/{albumKey:int}")]
    [CustomAuthFilter]
    public class ImageController : BaseController
    {
        #region Fields

        private readonly IImageAlbumService _imageAlbumService;
        private readonly IImageMapper _imageMapper;
        private readonly IMembershipService _membershipService;
        private readonly ISubscriptionService _subscriptionService;
        private readonly IFriendshipService _friendshipService;
        #endregion

        #region Constructors and Destructors

        public ImageController(
            IImageAlbumService imageAlbumService,
            IMembershipService membershipService,
            ISubscriptionService subscriptionService,
            IFriendshipService friendshipService,
            IImageMapper imageMapper)
        {
            this._membershipService = membershipService;
            this._imageAlbumService = imageAlbumService;
            this._subscriptionService = subscriptionService;
            this._imageMapper = imageMapper;
            this._friendshipService = friendshipService;
        }

        #endregion

        #region Public Methods and Operators

        [HttpGet]
        [Route("detailedview/{imageKey:int}")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult DetailedView(int? imageKey)
        {
            var result = new ImageDetailedViewModel();
            if (imageKey.HasValue)
            {
                try
                {
                    Image image = this._imageAlbumService.GetImageByKey(imageKey.Value);
                    if (image != null)
                    {
                        result = this._imageMapper.BuildDetailed(image);
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }

            return this.PartialView("_NavigationBarDetailedView", result);
        }

        [HttpGet]
        [AjaxRequestOnlyFilter]
        [ViewBagPopulatorFilter]
        [Route("editimage/{imageKey:int}")]
        public PartialViewResult EditImage(int? key, int? albumKey, int? imageKey)
        {
            ImageEditViewModel result;

            if (imageKey.HasValue)
            {
                try
                {
                    Image image = this._imageAlbumService.GetImageByKey(imageKey.Value);
                    if (image != null)
                    {
                        result = this._imageMapper.BuildEdit(image);
                    }
                    else
                    {
                        this.TempData[Constants.TempDataErrorMessage] = "Image is missing.";
                        return this.PartialView("_ErrorModal");
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }
            else
            {
                this.TempData[Constants.TempDataErrorMessage] = "Image is missing.";
                return this.PartialView("_ErrorModal");
            }

            return this.PartialView("_EditImage", result);
        }

        [HttpPost]
        [Route("editimage/{imageKey:int}")]
        [ViewBagPopulatorFilter]
        [AjaxRequestOnlyFilter]
        public ActionResult EditImage(int? albumKey, int? imageKey, ImageEditViewModel viewModel)
        {
            bool result = false;
            int key;
            if (!int.TryParse(ViewBag.Key, out key))
            {
                key = -1;
            }

            if (this.ModelState.IsValid && viewModel != null)
            {
                try
                {
                    User owner = this._membershipService.GetUserByKey(key);
                    Album album = this._imageAlbumService.GetAlbumByKey(albumKey.Value);
                    Image sourceImage = this._imageAlbumService.GetImageByKey(imageKey.Value);
                    if (sourceImage != null)
                    {
                        this._imageMapper.UpdateImage(sourceImage, viewModel);
                        this._imageAlbumService.UpdateImage(owner, album, sourceImage);
                    }

                    result = true;
                }
                catch (Exception)
                {
                    this.ModelState.AddModelError(string.Empty, Resources.Resources.OperationFailure);
                }
            }
            else
            {
                this.ModelState.AddModelError(string.Empty, Resources.Resources.OperationFailure);
            }

            if (result)
            {
                return this.Json(new { success = result });
            }

            return this.PartialView("_EditImage", viewModel);
        }

        [HttpGet]
        [ChildActionOnly]
        [Route("imageactions")]
        [ViewBagPopulatorFilter]
        public PartialViewResult ImageActions()
        {
            return this.PartialView("_ImageActions");
        }

        [HttpGet]
        [ChildActionOnly]
        [Route("imagenavigationbar/{imageKey:int}/actionlist")]
        [ViewBagPopulatorFilter]
        public PartialViewResult ImageNavbarActionList(int? imageKey)
        {
            return this.PartialView("_ImageNavbarActionList");
        }

        [HttpGet]
        [Route("imagenavigationbar/{imageKey:int}")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult ImageNavigationBar(int? imageKey)
        {
            return this.PartialView("_ImageNavigationSidebar");
        }

        [HttpGet]
        [Route("image/{imageKey:int}")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult ImagePreview(int? imageKey)
        {
            var result = new ImagePreviewViewModel();
            if (imageKey.HasValue)
            {
                try
                {
                    Image image = this._imageAlbumService.GetImageByKey(imageKey.Value);
                    if (image != null)
                    {
                        result = this._imageMapper.BuildPreview(image);
                    }
                }
                catch (Exception ex)
                {
                    this.TempData[Constants.TempDataErrorMessage] = ex.Message;
                    return this.PartialView("_ErrorModal");
                }
            }

            return this.PartialView("_ImagePreview", result);
        }

        [HttpGet]
        [ChildActionOnly]
        [Route("imageslider")]
        [ViewBagPopulatorFilter]
        public ActionResult ImageSlider(int? key, int? albumKey)
        {
            IList<ImageSliderViewModel> result = new List<ImageSliderViewModel>();
            try
            {
                User owner = this._membershipService.GetUserByKey(key.Value);
                Album album = this._imageAlbumService.GetAlbumByKey(albumKey.Value);
                if (owner != null && album != null)
                {
                    result =
                        this._imageAlbumService.GetAlbumImages(album)
                            .Select(p => this._imageMapper.BuildSlider(p))
                            .ToList();
                }
            }
            catch (Exception)
            {
            }

            return this.PartialView("_ImageSlider", result);
        }

        [HttpGet]
        [Route("image/index")]
        [ViewBagPopulatorFilter]
        public ActionResult Index(int? key)
        {
            this.UpdateSubscriptions(this._subscriptionService);
            this.UpdateFriendsList(this._friendshipService);
            this.ReleaseUpToDateSubscriptions(this._membershipService, this._subscriptionService);
            try
            {
                if (!(key.HasValue && this._membershipService.GetUserByKey(key.Value) != null))
                {
                    return this.RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                return this.RedirectToAction("Index", "Home");
            }

            return this.View();
        }

        [HttpGet]
        [Route("navigationbar")]
        [ViewBagPopulatorFilter]
        [ChildActionOnly]
        public PartialViewResult NavigationBar()
        {
            return this.PartialView("_NavigationSidebar");
        }

        [HttpGet]
        [Route("removeimage/{imageKey:int}")]
        [AjaxRequestOnlyFilter]
        public PartialViewResult RemoveImage(int? imageKey)
        {
            ImageEditViewModel result = null;
            if (imageKey.HasValue)
            {
                try
                {
                    Image image = this._imageAlbumService.GetImageByKey(imageKey.Value);
                    if (image != null)
                    {
                        result = this._imageMapper.BuildEdit(image);
                    }
                    else
                    {
                        this.TempData[Constants.TempDataErrorMessage] = "Image is missing.";
                        return this.PartialView("_ErrorModal");
                    }
                }
                catch (Exception ex)

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/Index.cshtml
@{
    ViewBag.Title = "Images";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row navbar-margin">
    <div class="col-md-3">
        @{Html.RenderAction("NavigationBar", "Image");}
    </div>
    <div id="user-image-list" class="col-md-9">
        <h1>Images</h1>
        @{Html.RenderAction("ImageSlider", "Image");}
    </div>
</div>

@section scripts
{
    <script type="text/javascript" src="~/Scripts/image/image.js"></script>
    <script type="text/javascript" src="~/Scripts/image/imageactions.js"></script>
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/ViewImage.cshtml
@{
    ViewBag.Title = "Images";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row navbar-margin">
    <div class="col-md-3">
        @{Html.RenderAction("ImageNavigationBar", "Image");}
    </div>
    <div id="user-image-list" class="col-md-9">
        @{Html.RenderAction("ImagePreview", "Image");}
    </div>
</div>

@section scripts
{
    <script type="text/javascript" src="~/Scripts/image/image.js"></script>
    <script type="text/javascript" src="~/Scripts/image/imageactions.js"></script>
    <script type="text/javascript" src="~/Scripts/comment/commentactions.js"></script>
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/_EditImage.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Image

@model ImageEditViewModel

<div class="modal fade" id="edit-image-modal" tabindex="-1" role="dialog" aria-labelledby="edit-image-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="edit-image-modal-header">Edit Image</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        @using (this.Html.BeginForm("EditImage", "Image", new { imageKey = Model.Key }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.HiddenFor(p => p.Key)
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    @(this.Html.ValidationSummary(true))
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <label for="inputName">Name</label>
                                    <p>@(this.Html.ValidationMessageFor(p => p.Name))</p>
                                    @(this.Html.TextBoxFor(p => p.Name, new { placeholder = "Name", @class = "form-control", id = "inputName" }))
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <label for="inputDescription">Description</label>
                                    <p>@(this.Html.ValidationMessageFor(p => p.Description))</p>
                                    @(this.Html.TextAreaFor(p => p.Description, new { placeholder = "Description", @class = "form-control", id = "inputDescription" }))
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <button class="btn btn-primary" type="submit"><i class="fa fa-cog fa-fw"></i> Edit</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/_ImageActions.cshtml
@using Antlr.Runtime.Tree
@using BSUIR.TermWork.ImageViewer.UI.WebSite.Helpers;

<li id="image-actions-list" class="active">
    <a href="#">Actions</a>
    <ul class="nav">
        @if (!ViewBag.IsVisitor)
        {
            <li>
                <a id="file-upload-link" href="#">
                    Upload file
                    @using (Html.BeginForm("UploadImage", "Image", FormMethod.Post, new { enctype = "multipart/form-data", @class = "upload-file-form", id = "file-upload-form" }))
                    {
                        <input id="file-uploader" name="uploadedImage" type="file" value="upload" />
                    }
                </a>
            </li>
        }
        else
        {
            this.Html.RenderAction("SubscribeOperation", "Subscription", new { key = ViewBag.Key });
        }
    </ul>
</li>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/_ImageNavbarActionList.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.Helpers;

@{
    string data = string.Concat(@"{ ""imageKey"": """, this.ViewBag.ImageKey, @"""  }");
}

<li id="image-actions-list" class="active">
    <a href="#">Actions</a>
    <ul class="nav">
        @if (!ViewBag.IsVisitor)
        {
            <li class="">
                @Html.AjaxLinkModalWindow("Edit", this.Url.Action("EditImage", "Image"), "edit-image-modal", "user-account-control", "", "fa fa-cogs pull-right", @data)
            </li>
        }
        else
        {
            this.Html.RenderAction("SubscribeOperation", "Subscription", new { key = ViewBag.Key });
        }
    </ul>
</li>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/_ImageNavigationSidebar.cshtml
<div class="bs-sidebar hidden-print affix" role="complementary">
    <ul class="nav bs-sidenav">
        @{this.Html.RenderAction("DetailedView", "Image", new { key = ViewBag.Key, albumKey = ViewBag.AlbumKey, imageKey = ViewBag.ImageKey });}
        @{this.Html.RenderAction("ImageNavbarActionList", "Image", new { key = ViewBag.Key, albumKey = ViewBag.AlbumKey, imageKey = ViewBag.ImageKey });}
        @{this.Html.RenderAction("Subscribers", "Subscription", new { key = ViewBag.Key });}
    </ul>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/_ImagePreview.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Image;

@model ImagePreviewViewModel

<div class="row">
    <div class="col-md-12">
        <img class="img-responsive" src="@Model.Content" alt="@Model.Name" />
    </div>
    <hr class="album-item-divider"/>
    @{this.Html.RenderAction("Comments", "Comment", new { key = ViewBag.Key, albumKey = ViewBag.AlbumKey, imageKey = ViewBag.ImageKey });}
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/_ImageSlider.cshtml
@using BSUIR.TermWork.ImageViewer.Model
@using BSUIR.TermWork.ImageViewer.UI.WebSite.Helpers
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Image

@model System.Collections.Generic.IList<ImageSliderViewModel>

@for (int i = 0; i < this.Model.Count; ++i)
{
    <div class="row well well-lg">
        <div class="col-md-7">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 data-key="@(this.Model[i].Key)">@(this.Model[i].Name)</h3>
                </div>
                <div class="panel-body">
                    <p align="justify">
                        @(this.Model[i].Description)
                    </p>
                </div>
            </div>
            <div class="btn-group">
                <a href="@Url.Action("ViewImage","Image", new { key = ViewBag.Key, albumKey = ViewBag.AlbumKey, imageKey = @Model[i].Key })"
                   class="btn btn-info">
                    <i class="fa fa-play">
                    </i> View
                </a>
                @if (!ViewBag.IsVisitor || this.User.IsInRole(RoleName.Administrator.ToString()))
                {
                    @(this.Html.AjaxModalWindow("Edit ", this.Url.Action("EditImage", "Image", new { imageKey = this.Model[i].Key }), "edit-image-modal", "user-account-control", "btn btn-info", "fa fa-edit", string.Concat(@"{ ""imageKey"": """, this.Model[i].Key, @"""  }")))
                }
            </div>
            @if (!ViewBag.IsVisitor || this.User.IsInRole(RoleName.Administrator.ToString()))
            {
                @(this.Html.AjaxModalWindow("Remove ", this.Url.Action("RemoveImage", "Image", new { imageKey = this.Model[i].Key }), "remove-image-modal", "user-account-control", "btn btn-danger pull-right", "fa fa-crosshairs", string.Concat(@"{ ""imageKey"": """, this.Model[i].Key, @"""  }")))
            }
        </div>
        <div class="col-md-5 pull-right">
            <img class="img-rounded" src="@(this.Model[i].Content)" alt="@(this.Model[i].Name)" />
        </div>
    </div>
    <hr class="album-item-divider" />
}

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/_NavigationBarDetailedView.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Image

@model ImageDetailedViewModel

<li class="active">
    <a href="#">@Model.Name</a>
    <ul class="nav">
        <li class=""><a href="@Url.Action("Index", "Image", new { key = ViewBag.Key, albumKey = ViewBag.AlbumKey })">Album: @Model.AlbumName</a></li>
        <li class=""><a href="@Url.Action("Index", "PersonalPage", new { key = ViewBag.Key} )">User: @Model.UserName</a></li>
        <li class=""><a>Rate: @Model.Rate</a></li>
        <li class=""><a>Upload date: @Model.UploadDate.ToShortDateString()</a></li>
    </ul>
</li>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/_NavigationSidebar.cshtml
<div class="bs-sidebar hidden-print affix" role="complementary">
    <ul class="nav bs-sidenav">
        @{ Html.RenderAction("DetailedView", "Album", new { key = ViewBag.Key, albumKey = ViewBag.AlbumKey });}
        @{ Html.RenderAction("ImageActions", "Image", new { key = ViewBag.Key, albumKey = ViewBag.AlbumKey });}
        @{ Html.RenderAction("Subscribers", "Subscription", new { key = ViewBag.Key });}
        @{ Html.RenderAction("OperationList", "Operation", new { key = ViewBag.Key }); }
        @{ Html.RenderAction("NotificationList", "Notification", new { key = ViewBag.Key }); }
        @{ Html.RenderAction("FriendsListNavbar", "Friendship", new { key = ViewBag.Key });}
    </ul>
</div>

BSUIR.TermWork.ImageViewer.UI.WebSite/Views/Image/_RemoveImage.cshtml
@using BSUIR.TermWork.ImageViewer.UI.WebSite.ViewModel.Image

@model ImageEditViewModel

<div class="modal fade" id="remove-image-modal" tabindex="-1" role="dialog" aria-labelledby="remove-image-modal-header" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="remove-image-modal-header">Remove Image</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row col-md-8">
                        @using (this.Html.BeginForm("RemoveImage", "Image", new { imageKey = Model.Key }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.HiddenFor(p => p.Key)
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <p>Do you really want to remove image?</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2">
                                    <button class="btn btn-danger" type="submit"><i class="fa fa-crosshairs fa-fw"></i> Remove</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>